[{"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2045", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2045/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2045/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2045/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2045", "id": 1336164448, "node_id": "I_kwDOAAqRMM5PpEBg", "number": 2045, "title": "[BUG] 'Cart' instance needs to have a primary key value before this relationship can be used.", "user": {"login": "Wladislav", "id": 2454823, "node_id": "MDQ6VXNlcjI0NTQ4MjM=", "avatar_url": "https://avatars.githubusercontent.com/u/2454823?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Wladislav", "html_url": "https://github.com/Wladislav", "followers_url": "https://api.github.com/users/Wladislav/followers", "following_url": "https://api.github.com/users/Wladislav/following{/other_user}", "gists_url": "https://api.github.com/users/Wladislav/gists{/gist_id}", "starred_url": "https://api.github.com/users/Wladislav/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Wladislav/subscriptions", "organizations_url": "https://api.github.com/users/Wladislav/orgs", "repos_url": "https://api.github.com/users/Wladislav/repos", "events_url": "https://api.github.com/users/Wladislav/events{/privacy}", "received_events_url": "https://api.github.com/users/Wladislav/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574963633, "node_id": "LA_kwDOAAqRMM7VFZ2x", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/needs%20triage", "name": "needs triage", "color": "BFDADC", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2022-08-11T15:55:35Z", "updated_at": "2022-09-19T10:44:40Z", "closed_at": "2022-09-19T10:42:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing Issues\n\n### Current Behavior\n\nI just installed the Mezzanine + cartridge to see its capabilities and got an error. \n\n### Expected Behavior\n\npages should be shown\r\n\n\n### Steps To Reproduce\n\nDjango version 4.1, using settings 'codesite.settings'\r\nStarting development server at http://*.*.*.*:8000/\r\n\r\nDjango Version: 4.1\r\nPython Version: 3.8.10\r\nInstalled Applications:\r\n('mezzanine.boot',\r\n'django.contrib.auth',\r\n'django.contrib.contenttypes',\r\n'django.contrib.redirects',\r\n'django.contrib.sessions',\r\n'django.contrib.sites',\r\n'django.contrib.sitemaps',\r\n'django.contrib.messages',\r\n'mezzanine.conf',\r\n'mezzanine.core',\r\n'mezzanine.generic',\r\n'mezzanine.pages',\r\n'cartridge.shop',\r\n'mezzanine.blog',\r\n'mezzanine.forms',\r\n'mezzanine.galleries',\r\n'filebrowser_safe',\r\n'grappelli_safe',\r\n'django.contrib.admin',\r\n'django.contrib.staticfiles',\r\n'django_comments')\r\nInstalled Middleware:\r\n('django.contrib.sessions.middleware.SessionMiddleware',\r\n'django.middleware.common.CommonMiddleware',\r\n'django.middleware.csrf.CsrfViewMiddleware',\r\n'django.contrib.auth.middleware.AuthenticationMiddleware',\r\n'django.contrib.messages.middleware.MessageMiddleware',\r\n'django.middleware.clickjacking.XFrameOptionsMiddleware',\r\n'cartridge.shop.middleware.ShopMiddleware',\r\n'mezzanine.core.request.CurrentRequestMiddleware',\r\n'mezzanine.core.middleware.RedirectFallbackMiddleware',\r\n'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',\r\n'mezzanine.core.middleware.SitePermissionMiddleware',\r\n'mezzanine.pages.middleware.PageMiddleware')\r\n\r\nTemplate error:\r\nIn template /home/vlad/anycoderu/cartridge/cartridge/shop/templates/shop/includes/user_panel.html, error at line 5\r\n'Cart' instance needs to have a primary key value before this relationship can be used.\r\n1 : {% load i18n shop_tags mezzanine_tags %}\r\n2 : {% spaceless %}\r\n3 : <a href=\"{% url \"shop_cart\" %}\">\r\n4 :\r\n5 : {% blocktrans count request.cart.total_quantity as cart_quantity %} 1 item{% plural %}{{ cart_quantity }} items{% endblocktrans %}\r\n6 : {% trans \"in cart\" %}:\r\n7 : {{ request.cart.total_price|currency }}\r\n\r\n8 : {% if request.cart.total_quantity != 0 %}\r\n9 : <a href=\"{% url \"shop_checkout\" %}\" class=\"btn btn-primary\">\r\n10 : {% if request.session.order.step %}{% trans \"Return to Checkout\" %}{% else %}{% trans \"Go to Checkout\" %}{% endif %}\r\n11 :\r\n\r\n12 : {% endif %}\r\n13 : {% if settings.SHOP_USE_WISHLIST %}\r\n14 : <a href=\"{% url \"shop_wishlist\" %}\" class=\"btn-wishlist\">\r\n15 :\r\n\r\nTraceback (most recent call last):\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/core/handlers/exception.py\", line 55, in inner\r\nresponse = get_response(request)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/core/handlers/base.py\", line 220, in _get_response\r\nresponse = response.render()\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/response.py\", line 114, in render\r\nself.content = self.rendered_content\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/response.py\", line 92, in rendered_content\r\nreturn template.render(context, self._request)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/backends/django.py\", line 62, in render\r\nreturn self.template.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 175, in render\r\nreturn self._render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 167, in _render\r\nreturn self.nodelist.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/loader_tags.py\", line 157, in render\r\nreturn compiled_parent._render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 167, in _render\r\nreturn self.nodelist.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/mezzanine/template/init.py\", line 95, in render\r\nargs = (self.nodelist.render(context), context, token)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/loader_tags.py\", line 208, in render\r\nreturn template.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 177, in render\r\nreturn self._render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 167, in _render\r\nreturn self.nodelist.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/defaulttags.py\", line 322, in render\r\nreturn nodelist.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/loader_tags.py\", line 208, in render\r\nreturn template.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 177, in render\r\nreturn self._render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 167, in _render\r\nreturn self.nodelist.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/defaulttags.py\", line 415, in render\r\nreturn strip_spaces_between_tags(self.nodelist.render(context).strip())\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in render\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 1005, in\r\nreturn SafeString(\"\".join([node.render_annotated(context) for node in self]))\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 966, in render_annotated\r\nreturn self.render(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/templatetags/i18n.py\", line 160, in render\r\ncount = self.counter.resolve(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 715, in resolve\r\nobj = self.var.resolve(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 847, in resolve\r\nvalue = self._resolve_lookup(context)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/template/base.py\", line 914, in _resolve_lookup\r\ncurrent = current()\r\nFile \"/home/vlad/anycoderu/cartridge/cartridge/shop/models.py\", line 643, in total_quantity\r\nreturn sum(item.quantity for item in self)\r\nFile \"/home/vlad/anycoderu/cartridge/cartridge/shop/models.py\", line 610, in iter\r\nself._cached_items = self.items.all()\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/db/models/fields/related_descriptors.py\", line 596, in get\r\ninstance_cache[key] = self.related_manager_cls(instance)\r\nFile \"/home/vlad/anycoderu/anycodenv/lib/python3.8/site-packages/Django-4.1-py3.8.egg/django/db/models/fields/related_descriptors.py\", line 634, in init\r\nraise ValueError(\r\n\r\nException Type: ValueError at /\r\nException Value: 'Cart' instance needs to have a primary key value before this relationship can be used.\n\n### Environment\n\n```markdown\nDjango Version: 4.1\r\nPython Version: 3.8.10\n```\n\n\n### Anything else?\n\n_No response_", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2045/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2045/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2022", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2022/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2022/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2022/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2022", "id": 1144889554, "node_id": "I_kwDOAAqRMM5EPaDS", "number": 2022, "title": "[BUG] Docs about themes link to cybersquatted domain", "user": {"login": "toobaz", "id": 1224492, "node_id": "MDQ6VXNlcjEyMjQ0OTI=", "avatar_url": "https://avatars.githubusercontent.com/u/1224492?v=4", "gravatar_id": "", "url": "https://api.github.com/users/toobaz", "html_url": "https://github.com/toobaz", "followers_url": "https://api.github.com/users/toobaz/followers", "following_url": "https://api.github.com/users/toobaz/following{/other_user}", "gists_url": "https://api.github.com/users/toobaz/gists{/gist_id}", "starred_url": "https://api.github.com/users/toobaz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/toobaz/subscriptions", "organizations_url": "https://api.github.com/users/toobaz/orgs", "repos_url": "https://api.github.com/users/toobaz/repos", "events_url": "https://api.github.com/users/toobaz/events{/privacy}", "received_events_url": "https://api.github.com/users/toobaz/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574737125, "node_id": "LA_kwDOAAqRMM7VEijl", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/released", "name": "released", "color": "0E8A16", "default": false, "description": ""}, {"id": 3574963633, "node_id": "LA_kwDOAAqRMM7VFZ2x", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/needs%20triage", "name": "needs triage", "color": "BFDADC", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-02-20T01:20:42Z", "updated_at": "2022-02-22T15:00:02Z", "closed_at": "2022-02-21T19:52:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing Issues\n\n### Current Behavior\n\nhttp://mezzanine.jupo.org/docs/overview.html contains, under \"Themes\", a link that actually points to a cybersquatted domain.\n\n### Expected Behavior\n\nI would expect the link to be updated, or the sentence removed.\n\n### Steps To Reproduce\n\nJust visit the docs and click the link.\n\n### Environment\n\n```markdown\nOnline. I've checked that the link is also present in the git version of the page.\n```\n\n\n### Anything else?\n\n_No response_", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2022/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2022/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2019", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2019/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2019/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2019/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2019", "id": 1125093730, "node_id": "I_kwDOAAqRMM5DD5Fi", "number": 2019, "title": "[BUG] __init__() missing 1 required positional argument: 'get_response'", "user": {"login": "DatCGI2net", "id": 7017649, "node_id": "MDQ6VXNlcjcwMTc2NDk=", "avatar_url": "https://avatars.githubusercontent.com/u/7017649?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DatCGI2net", "html_url": "https://github.com/DatCGI2net", "followers_url": "https://api.github.com/users/DatCGI2net/followers", "following_url": "https://api.github.com/users/DatCGI2net/following{/other_user}", "gists_url": "https://api.github.com/users/DatCGI2net/gists{/gist_id}", "starred_url": "https://api.github.com/users/DatCGI2net/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DatCGI2net/subscriptions", "organizations_url": "https://api.github.com/users/DatCGI2net/orgs", "repos_url": "https://api.github.com/users/DatCGI2net/repos", "events_url": "https://api.github.com/users/DatCGI2net/events{/privacy}", "received_events_url": "https://api.github.com/users/DatCGI2net/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574737125, "node_id": "LA_kwDOAAqRMM7VEijl", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/released", "name": "released", "color": "0E8A16", "default": false, "description": ""}, {"id": 3574963633, "node_id": "LA_kwDOAAqRMM7VFZ2x", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/needs%20triage", "name": "needs triage", "color": "BFDADC", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2022-02-06T03:31:30Z", "updated_at": "2022-02-22T14:59:59Z", "closed_at": "2022-02-22T14:47:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing Issues\n\n### Current Behavior\n\nWhen setting cache for django, the issue is arosen.\n\n### Expected Behavior\n\nIt should be working when settings cache for django.\n\n### Steps To Reproduce\n\n1. Set cache in django settings like below\r\n2. Visit any pages, including admin\r\n\r\nCACHES = {\r\n    \"default\": {\r\n        \"BACKEND\": \"django.core.cache.backends.redis.RedisCache\",\r\n        \"LOCATION\": \"redis://127.0.0.1:6379\",\r\n    }\r\n}\n\n### Environment\n\n```markdown\nEnvironment:\r\n\r\n\r\nRequest Method: GET\r\nRequest URL: http://127.0.0.1:8000/admin/pages/richtextpage/2/change/\r\n\r\nDjango Version: 4.0.2\r\nPython Version: 3.8.10\r\nInstalled Applications:\r\n('mezzanine.boot',\r\n 'django.contrib.auth',\r\n 'django.contrib.contenttypes',\r\n 'django.contrib.redirects',\r\n 'django.contrib.sessions',\r\n 'django.contrib.sites',\r\n 'django.contrib.sitemaps',\r\n 'django.contrib.messages',\r\n 'mezzanine.conf',\r\n 'mezzanine.core',\r\n 'mezzanine.generic',\r\n 'mezzanine.pages',\r\n 'mezzanine.blog',\r\n 'mezzanine.forms',\r\n 'mezzanine.galleries',\r\n 'mezzanine.twitter',\r\n 'mezzanine.accounts',\r\n 'modeltranslation',\r\n 'django_extensions',\r\n 'theme',\r\n 'payment',\r\n 'paypal.standard.ipn',\r\n 'tocheckout.tocheckout',\r\n 'filebrowser_safe',\r\n 'grappelli_safe',\r\n 'django.contrib.admin',\r\n 'django.contrib.staticfiles',\r\n 'django_comments')\r\nInstalled Middleware:\r\n('mezzanine.core.middleware.UpdateCacheMiddleware',\r\n 'django.contrib.sessions.middleware.SessionMiddleware',\r\n 'django.middleware.locale.LocaleMiddleware',\r\n 'django.middleware.common.CommonMiddleware',\r\n 'django.middleware.csrf.CsrfViewMiddleware',\r\n 'django.contrib.auth.middleware.AuthenticationMiddleware',\r\n 'django.contrib.messages.middleware.MessageMiddleware',\r\n 'django.middleware.clickjacking.XFrameOptionsMiddleware',\r\n 'mezzanine.core.request.CurrentRequestMiddleware',\r\n 'mezzanine.core.middleware.RedirectFallbackMiddleware',\r\n 'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',\r\n 'mezzanine.core.middleware.SitePermissionMiddleware',\r\n 'mezzanine.pages.middleware.PageMiddleware',\r\n 'mezzanine.core.middleware.FetchFromCacheMiddleware')\r\n\r\n\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/dat/.venv3/mezz3/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\r\n    response = get_response(request)\r\n  File \"/home/dat/.venv3/mezz3/lib/python3.8/site-packages/django/utils/deprecation.py\", line 125, in __call__\r\n    response = self.process_request(request)\r\n  File \"/home/dat/.venv3/mezz3/lib/python3.8/site-packages/mezzanine/core/middleware.py\", line 244, in process_request\r\n    csrf_mw = CsrfViewMiddleware()\r\n\r\nException Type: TypeError at /admin/pages/richtextpage/2/change/\r\nException Value: __init__() missing 1 required positional argument: 'get_response'\n```\n\n\n### Anything else?\n\n_No response_", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2019/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2019/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2018", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2018/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2018/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2018/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2018", "id": 1113369019, "node_id": "I_kwDOAAqRMM5CXKm7", "number": 2018, "title": "[BUG] SitePermissionUserAdminForm: Verifying that a User with the same email already exists, use exists instead of get.", "user": {"login": "ytyng", "id": 1742861, "node_id": "MDQ6VXNlcjE3NDI4NjE=", "avatar_url": "https://avatars.githubusercontent.com/u/1742861?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ytyng", "html_url": "https://github.com/ytyng", "followers_url": "https://api.github.com/users/ytyng/followers", "following_url": "https://api.github.com/users/ytyng/following{/other_user}", "gists_url": "https://api.github.com/users/ytyng/gists{/gist_id}", "starred_url": "https://api.github.com/users/ytyng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ytyng/subscriptions", "organizations_url": "https://api.github.com/users/ytyng/orgs", "repos_url": "https://api.github.com/users/ytyng/repos", "events_url": "https://api.github.com/users/ytyng/events{/privacy}", "received_events_url": "https://api.github.com/users/ytyng/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574737125, "node_id": "LA_kwDOAAqRMM7VEijl", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/released", "name": "released", "color": "0E8A16", "default": false, "description": ""}, {"id": 3574963633, "node_id": "LA_kwDOAAqRMM7VFZ2x", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/needs%20triage", "name": "needs triage", "color": "BFDADC", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-01-25T03:05:16Z", "updated_at": "2022-02-22T15:00:05Z", "closed_at": "2022-02-21T19:51:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing Issues\r\n\r\n### Current Behavior\r\n\r\nhttps://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/admin.py#L412\r\n\r\nin SitePermissionUserAdminForm,\r\nIf there are multiple records for users with the same email,\r\nRaises `MultipleObjectsReturned`, and no catched.\r\n\r\n\r\n\r\n\r\n### Expected Behavior\r\n\r\nRaises `ValidationError(_(\"This email is already registered\"))`\r\n\r\n\r\n### Steps To Reproduce\r\n\r\n1. Multiple records for users with the same email exists,\r\n2. Save user admin page.\r\n\r\n![MultipleObjectsReturned_at__admin_user_user_42_change_](https://user-images.githubusercontent.com/1742861/150902688-aa96eba7-c02f-4059-b9cb-58db5a7f3e48.png)\r\n\r\n\r\n\r\n### Environment\r\n\r\n```markdown\r\n- Operating System: MacOS, Ubuntu\r\n- Python version: 3.8\r\n- Django version: 3.2\r\n- Database engine and version: MySQL 5.7\r\n- Mezzanine version: 5.0.0 (85564606d4594f027b9ad7ff38c576a9bdd3096d)\r\n```\r\n\r\n\r\n### Anything else?\r\n\r\nhttps://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/admin.py#L412\r\n\r\nI think\r\n```python\r\n        try:\r\n            User.objects.exclude(id=form.instance.id).get(email=email)\r\n        except User.DoesNotExist:\r\n            return email\r\n        raise ValidationError(_(\"This email is already registered\"))\r\n```\r\n\r\nChange to\r\n```python\r\n        if User.objects.exclude(id=form.instance.id).filter(email=email).exists():\r\n            raise ValidationError(_(\"This email is already registered\"))\r\n        return email\r\n```", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2018/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2018/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2016", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2016/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2016/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2016/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2016", "id": 1102394107, "node_id": "I_kwDOAAqRMM5BtTL7", "number": 2016, "title": "[BUG] `set_dynamic_settings` always sets the MySQL test database collation to `utf8_general_ci`", "user": {"login": "gabriellesc", "id": 5559014, "node_id": "MDQ6VXNlcjU1NTkwMTQ=", "avatar_url": "https://avatars.githubusercontent.com/u/5559014?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gabriellesc", "html_url": "https://github.com/gabriellesc", "followers_url": "https://api.github.com/users/gabriellesc/followers", "following_url": "https://api.github.com/users/gabriellesc/following{/other_user}", "gists_url": "https://api.github.com/users/gabriellesc/gists{/gist_id}", "starred_url": "https://api.github.com/users/gabriellesc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gabriellesc/subscriptions", "organizations_url": "https://api.github.com/users/gabriellesc/orgs", "repos_url": "https://api.github.com/users/gabriellesc/repos", "events_url": "https://api.github.com/users/gabriellesc/events{/privacy}", "received_events_url": "https://api.github.com/users/gabriellesc/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574737125, "node_id": "LA_kwDOAAqRMM7VEijl", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/released", "name": "released", "color": "0E8A16", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2022-01-13T21:19:46Z", "updated_at": "2022-01-14T16:17:01Z", "closed_at": "2022-01-14T05:46:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing Issues\r\n\r\n### Current Behavior\r\n\r\nFor MySQL databases, the `set_dynamic_settings` util always sets the MySQL test database collation to `utf8_general_ci`: https://github.com/stephenmcd/mezzanine/blob/001a16b052578ba8b29e847a1949dcdee5b400f6/mezzanine/utils/conf.py#L250\r\nUnfortunately, the `utf8_general_ci` collation is only compatible with the `utf8` charset, which means that it is not possible to run tests with a test database that uses a different charset, eg. `utf8mb4_*` charsets. When attempting to do so, we see an error like:\r\n```\r\n(1253, \"COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'\")\r\n```\r\n\r\n### Expected Behavior\r\n\r\nWe should be able to set the test database collation in the app settings and have the `set_dynamic_settings` util respect that, rather than overriding it.\r\n\r\n### Steps To Reproduce\r\n\r\nHere is a repo containing a sample Django app with mezzanine, that demonstrates the issue: https://github.com/bevy/mezzanine-fix-demo\r\nFollowing the steps in the repo and running `tox`, you can see that the error occurs with mezzanine 5.1.0 and both Django 2.2 and 3.2 (but does *not* occur when using a [version of mezzanine](https://github.com/stephenmcd/mezzanine/commit/06281cf9c030e17f342d2eed1c3b267728c07870) that defers to the test database collation in the app settings).\r\n\r\n### Environment\r\n\r\n```markdown\r\n- Operating System: macOS Big Sur/Ubuntu 18.04 \r\n- Python version: 3.7\r\n- Django version: 2.2/3.2\r\n- Database engine and version: MySQL 5.7\r\n- Mezzanine version: 5.1.0\r\n```\r\n\r\n\r\n### Anything else?\r\n\r\nThis commit exists to fix the issue, but hasn't been merged yet! https://github.com/stephenmcd/mezzanine/commit/06281cf9c030e17f342d2eed1c3b267728c07870", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2016/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2016/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2013", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2013/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2013/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2013/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2013", "id": 1093811778, "node_id": "I_kwDOAAqRMM5BMj5C", "number": 2013, "title": "[BUG] Missing comma from fieldset \"fields\" value", "user": {"login": "code-review-doctor", "id": 72647856, "node_id": "MDQ6VXNlcjcyNjQ3ODU2", "avatar_url": "https://avatars.githubusercontent.com/u/72647856?v=4", "gravatar_id": "", "url": "https://api.github.com/users/code-review-doctor", "html_url": "https://github.com/code-review-doctor", "followers_url": "https://api.github.com/users/code-review-doctor/followers", "following_url": "https://api.github.com/users/code-review-doctor/following{/other_user}", "gists_url": "https://api.github.com/users/code-review-doctor/gists{/gist_id}", "starred_url": "https://api.github.com/users/code-review-doctor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/code-review-doctor/subscriptions", "organizations_url": "https://api.github.com/users/code-review-doctor/orgs", "repos_url": "https://api.github.com/users/code-review-doctor/repos", "events_url": "https://api.github.com/users/code-review-doctor/events{/privacy}", "received_events_url": "https://api.github.com/users/code-review-doctor/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574737125, "node_id": "LA_kwDOAAqRMM7VEijl", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/released", "name": "released", "color": "0E8A16", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2022-01-04T22:41:54Z", "updated_at": "2022-01-05T20:29:07Z", "closed_at": "2022-01-05T17:37:42Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing Issues\n\n### Current Behavior\n\nMissing comma from fieldset \"fields\" value on line 471:\r\n\r\nhttps://github.com/stephenmcd/mezzanine/blob/b407cb70ff66684e0511b827234e103259a91d4c/tests/test_core.py#L468-L472\r\n\r\nthis results in the fieldset fields being a `str` rather than a tuple (a single item tuple requires a comma otherwise python willn not know it's a tuple. It's a comma that makes the tuple, not paren).\r\n\r\nFunnily enough - the reason the tests pass is the field name is a single character \"c\", so when Django loops over the string, it finds one item: \"c\".If the field name had two chars then the bug would present itself.\r\n\r\n\n\n### Expected Behavior\n\nfieldset `fields` should be a tuple like so\r\n```\r\n     (\"Fieldset 3\", {\"fields\": (\"c\",)}), \r\n```\n\n### Steps To Reproduce\n\nNA\n\n### Environment\n\n```markdown\nNA\n```\n\n\n### Anything else?\n\nI am a static analysis tool, and found this issue while integration testing new checks against various codebases - this one included.", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2013/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2013/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2008", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2008/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2008/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2008/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2008", "id": 1083934373, "node_id": "I_kwDOAAqRMM5Am4al", "number": 2008, "title": "[BUG] cannot import name 'url' from 'django.conf.urls'", "user": {"login": "tswfi", "id": 1352132, "node_id": "MDQ6VXNlcjEzNTIxMzI=", "avatar_url": "https://avatars.githubusercontent.com/u/1352132?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tswfi", "html_url": "https://github.com/tswfi", "followers_url": "https://api.github.com/users/tswfi/followers", "following_url": "https://api.github.com/users/tswfi/following{/other_user}", "gists_url": "https://api.github.com/users/tswfi/gists{/gist_id}", "starred_url": "https://api.github.com/users/tswfi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tswfi/subscriptions", "organizations_url": "https://api.github.com/users/tswfi/orgs", "repos_url": "https://api.github.com/users/tswfi/repos", "events_url": "https://api.github.com/users/tswfi/events{/privacy}", "received_events_url": "https://api.github.com/users/tswfi/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574737125, "node_id": "LA_kwDOAAqRMM7VEijl", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/released", "name": "released", "color": "0E8A16", "default": false, "description": ""}, {"id": 3574963633, "node_id": "LA_kwDOAAqRMM7VFZ2x", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/needs%20triage", "name": "needs triage", "color": "BFDADC", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2021-12-18T19:57:40Z", "updated_at": "2022-01-05T20:29:04Z", "closed_at": "2021-12-30T01:14:05Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing Issues\n\n### Current Behavior\n\nfollowing the \"quick start\" info from the homepage and going around bug #2007 by manually installing pytz with\r\n\r\n```\r\npipenv install pytz\r\n```\r\n\r\nComes the next problem:\r\n\r\n```\r\ndemo> ./manage.py createdb\r\nTraceback (most recent call last):\r\n  File \"/home/tsw/git/mezzazine_vanilla/myproject/./manage.py\", line 14, in <module>\r\n    execute_from_command_line(sys.argv)\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/django/core/management/__init__.py\", line 425, in execute_from_command_line\r\n    utility.execute()\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/django/core/management/__init__.py\", line 401, in execute\r\n    django.setup()\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/django/__init__.py\", line 24, in setup\r\n    apps.populate(settings.INSTALLED_APPS)\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/django/apps/registry.py\", line 91, in populate\r\n    app_config = AppConfig.create(entry)\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/django/apps/config.py\", line 223, in create\r\n    import_module(entry)\r\n  File \"/usr/lib64/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/mezzanine/boot/__init__.py\", line 18, in <module>\r\n    from mezzanine.boot.lazy_admin import LazyAdminSite\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/mezzanine/boot/lazy_admin.py\", line 2, in <module>\r\n    from django.conf.urls import include, url\r\nImportError: cannot import name 'url' from 'django.conf.urls' (/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/django/conf/urls/__init__.py)\r\ndemo> \r\n```\n\n### Expected Behavior\n\nThe database is created with the command `manage.py createdb`\n\n### Steps To Reproduce\n\nfollow the quick start from homepage. Work around #2007 by also installing `pytz`\n\n### Environment\n\n```markdown\n- Operating System: linux\r\n- Python version: 3.9.9\r\n- Django version: 4.0.0\r\n- Database engine and version: I'm guessing the \"quick start\" from homepage defaults to sqlite? didn't get that far.\r\n- Mezzanine version: 5.0.0\n```\n\n\n### Anything else?\n\nI'm guessing this comes from the fact that django has deprecated django.conf.urls.url in version 3.1 (https://docs.djangoproject.com/en/3.2/ref/urls/#url) and django.urls.re_path() should be used instead. Of course migrating to the new `path` format might be even better as it is much nicer to read (https://docs.djangoproject.com/en/4.0/ref/urls/)", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2008/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2008/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2007", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2007/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2007/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2007/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/2007", "id": 1083932868, "node_id": "I_kwDOAAqRMM5Am4DE", "number": 2007, "title": "[BUG] pytz not defined as a requirement, thus \"quick start\" instructions on homepage fail", "user": {"login": "tswfi", "id": 1352132, "node_id": "MDQ6VXNlcjEzNTIxMzI=", "avatar_url": "https://avatars.githubusercontent.com/u/1352132?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tswfi", "html_url": "https://github.com/tswfi", "followers_url": "https://api.github.com/users/tswfi/followers", "following_url": "https://api.github.com/users/tswfi/following{/other_user}", "gists_url": "https://api.github.com/users/tswfi/gists{/gist_id}", "starred_url": "https://api.github.com/users/tswfi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tswfi/subscriptions", "organizations_url": "https://api.github.com/users/tswfi/orgs", "repos_url": "https://api.github.com/users/tswfi/repos", "events_url": "https://api.github.com/users/tswfi/events{/privacy}", "received_events_url": "https://api.github.com/users/tswfi/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}, {"id": 3574963633, "node_id": "LA_kwDOAAqRMM7VFZ2x", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/needs%20triage", "name": "needs triage", "color": "BFDADC", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2021-12-18T19:48:57Z", "updated_at": "2021-12-30T01:16:16Z", "closed_at": "2021-12-30T01:16:16Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing Issues\n\n### Current Behavior\n\nPytz is not installed by default. Following the \"quick start\" instructions from homepage:\r\n\r\n```\r\ndemo> pipenv install mezzanine\r\nInstalling mezzanine...\r\nAdding mezzanine to Pipfile's [packages]...\r\n\u2714 Installation Succeeded \r\nPipfile.lock not found, creating...\r\nLocking [dev-packages] dependencies...\r\nLocking [packages] dependencies...\r\nBuilding requirements...\r\nResolving dependencies...\r\n\u2714 Success! \r\nUpdated Pipfile.lock (9c2e16)!\r\nInstalling dependencies from Pipfile.lock (9c2e16)...\r\n  \ud83d\udc0d   \u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589\u2589 0/0 \u2014 00:00:00\r\ndemo> mezzanine-project myproject\r\ndemo> cd myproject\r\ndemo> python manage.py createdb\r\nTraceback (most recent call last):\r\n  File \"/home/tsw/git/mezzazine_vanilla/myproject/manage.py\", line 7, in <module>\r\n    from mezzanine.utils.conf import real_project_name\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/mezzanine/utils/conf.py\", line 11, in <module>\r\n    from mezzanine.utils.timezone import get_best_local_timezone\r\n  File \"/home/tsw/.local/share/virtualenvs/mezzazine_vanilla-ZPLJQPDu/lib/python3.9/site-packages/mezzanine/utils/timezone.py\", line 4, in <module>\r\n    import pytz\r\nModuleNotFoundError: No module named 'pytz'\r\ndemo> \r\n```\r\n\r\npytz-deprecation-shim seems to be installed but is probably not enough\r\n\r\n```\r\ndemo> pipenv graph\r\nMezzanine==5.0.0\r\n  - beautifulsoup4 [required: >=4.5.3, installed: 4.10.0]\r\n    - soupsieve [required: >1.2, installed: 2.3.1]\r\n  - bleach [required: >=2, installed: 4.1.0]\r\n    - packaging [required: Any, installed: 21.3]\r\n      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.6]\r\n    - six [required: >=1.9.0, installed: 1.16.0]\r\n    - webencodings [required: Any, installed: 0.5.1]\r\n  - chardet [required: >=4, installed: 4.0.0]\r\n  - django [required: >=2.2, installed: 4.0]\r\n    - asgiref [required: >=3.4.1,<4, installed: 3.4.1]\r\n    - sqlparse [required: >=0.2.2, installed: 0.4.2]\r\n  - django-contrib-comments [required: >=1.9, installed: 2.1.0]\r\n    - Django [required: >=2.2, installed: 4.0]\r\n      - asgiref [required: >=3.4.1,<4, installed: 3.4.1]\r\n      - sqlparse [required: >=0.2.2, installed: 0.4.2]\r\n  - filebrowser-safe [required: >=1.0.0, installed: 1.0.0]\r\n  - grappelli-safe [required: >=1.0.0, installed: 1.0.0]\r\n  - pillow [required: >=7, installed: 8.4.0]\r\n  - requests [required: >=2.1.0, installed: 2.26.0]\r\n    - certifi [required: >=2017.4.17, installed: 2021.10.8]\r\n    - charset-normalizer [required: ~=2.0.0, installed: 2.0.9]\r\n    - idna [required: >=2.5,<4, installed: 3.3]\r\n    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.7]\r\n  - requests-oauthlib [required: >=1.3, installed: 1.3.0]\r\n    - oauthlib [required: >=3.0.0, installed: 3.1.1]\r\n    - requests [required: >=2.0.0, installed: 2.26.0]\r\n      - certifi [required: >=2017.4.17, installed: 2021.10.8]\r\n      - charset-normalizer [required: ~=2.0.0, installed: 2.0.9]\r\n      - idna [required: >=2.5,<4, installed: 3.3]\r\n      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.7]\r\n  - tzlocal [required: >=2, installed: 4.1]\r\n    - pytz-deprecation-shim [required: Any, installed: 0.1.0.post0]\r\n      - tzdata [required: Any, installed: 2021.5]\r\ndemo> \r\n```\n\n### Expected Behavior\n\n\"quick start\" from homepage works\n\n### Steps To Reproduce\n\nfollow the \"quick start\" instructions from the homepage\n\n### Environment\n\n```markdown\n- Operating System: linux\r\n- Python version: 3.9.9\r\n- Django version: 4.0.0 (comes automatically as it is defined as a requirement for mezzanine, see pipenv graph)\r\n- Database engine and version: I'm guessing the \"quick start\" defaults to sqlite?\r\n- Mezzanine version: 5.0.0\n```\n\n\n### Anything else?\n\nI'm guessing this comes from the fact that Django 4.0.0 was just released and it moved away from pytz (https://docs.djangoproject.com/en/4.0/releases/4.0/#zoneinfo-default-timezone-implementation)\r\n\r\nmezzanine requirements define Django > 2.2 but no upper limit (https://github.com/stephenmcd/mezzanine/blob/master/setup.cfg#L43)", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2007/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/2007/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1580", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1580/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1580/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1580/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/1580", "id": 145834752, "node_id": "MDU6SXNzdWUxNDU4MzQ3NTI=", "number": 1580, "title": "Thumbnail template tag saves thumbnail to MEDIA_URL using urlencoded path", "user": {"login": "emenendez", "id": 3814114, "node_id": "MDQ6VXNlcjM4MTQxMTQ=", "avatar_url": "https://avatars.githubusercontent.com/u/3814114?v=4", "gravatar_id": "", "url": "https://api.github.com/users/emenendez", "html_url": "https://github.com/emenendez", "followers_url": "https://api.github.com/users/emenendez/followers", "following_url": "https://api.github.com/users/emenendez/following{/other_user}", "gists_url": "https://api.github.com/users/emenendez/gists{/gist_id}", "starred_url": "https://api.github.com/users/emenendez/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/emenendez/subscriptions", "organizations_url": "https://api.github.com/users/emenendez/orgs", "repos_url": "https://api.github.com/users/emenendez/repos", "events_url": "https://api.github.com/users/emenendez/events{/privacy}", "received_events_url": "https://api.github.com/users/emenendez/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-04-04T23:40:33Z", "updated_at": "2016-05-30T06:37:45Z", "closed_at": "2016-05-30T06:37:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "When using the thumbnail template tag in a site which also uses the s3boto file-storage backend to store all media files in an S3-backed CDN, files containing any characters which are urlencoded result in broken thumbnail links. This seems to be because the thumbnail tag code saves the auto-generated thumbnail to S3 using a urlencoded path (https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templatetags/mezzanine_tags.py#L400), but the s3boto backend does not expect this and does not un-encode it. Therefore, files are saved to S3 with with names such as \"image-%23fff.png\" instead of \"image-#fff.png\" and links to these files from the pages themselves are broken.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1580/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1580/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1575", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1575/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1575/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1575/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/1575", "id": 145079818, "node_id": "MDU6SXNzdWUxNDUwNzk4MTg=", "number": 1575, "title": "Cannot add new stacked inlines", "user": {"login": "jerivas", "id": 2391102, "node_id": "MDQ6VXNlcjIzOTExMDI=", "avatar_url": "https://avatars.githubusercontent.com/u/2391102?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jerivas", "html_url": "https://github.com/jerivas", "followers_url": "https://api.github.com/users/jerivas/followers", "following_url": "https://api.github.com/users/jerivas/following{/other_user}", "gists_url": "https://api.github.com/users/jerivas/gists{/gist_id}", "starred_url": "https://api.github.com/users/jerivas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jerivas/subscriptions", "organizations_url": "https://api.github.com/users/jerivas/orgs", "repos_url": "https://api.github.com/users/jerivas/repos", "events_url": "https://api.github.com/users/jerivas/events{/privacy}", "received_events_url": "https://api.github.com/users/jerivas/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 12, "created_at": "2016-04-01T03:49:00Z", "updated_at": "2016-08-19T05:36:22Z", "closed_at": "2016-08-19T05:36:22Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "So I was giving the master branch a shot and noticed that we're now using Django's own Javascript to dynamically insert/remove inlines (yay!). It seems to be working fine, except that instances of `StackedDynamicInlineAdmin` don't get the \"Add another\" link.\n\nI'm using Django 1.9.4 and Mezzanine master (with grappelli-safe master too).\n\nI actually encountered this after developing a fix for a weird issue where stacked inlines were not being ordered by drag-n-drop. I hope to contribute that once we can sort this out.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1575/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1575/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1565", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1565/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1565/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1565/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/1565", "id": 141439737, "node_id": "MDU6SXNzdWUxNDE0Mzk3Mzc=", "number": 1565, "title": "Keyword field loses current value when Page form is invalid", "user": {"login": "stephenmcd", "id": 116385, "node_id": "MDQ6VXNlcjExNjM4NQ==", "avatar_url": "https://avatars.githubusercontent.com/u/116385?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stephenmcd", "html_url": "https://github.com/stephenmcd", "followers_url": "https://api.github.com/users/stephenmcd/followers", "following_url": "https://api.github.com/users/stephenmcd/following{/other_user}", "gists_url": "https://api.github.com/users/stephenmcd/gists{/gist_id}", "starred_url": "https://api.github.com/users/stephenmcd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stephenmcd/subscriptions", "organizations_url": "https://api.github.com/users/stephenmcd/orgs", "repos_url": "https://api.github.com/users/stephenmcd/repos", "events_url": "https://api.github.com/users/stephenmcd/events{/privacy}", "received_events_url": "https://api.github.com/users/stephenmcd/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-03-17T00:18:26Z", "updated_at": "2017-05-31T01:38:36Z", "closed_at": "2017-05-31T01:38:36Z", "author_association": "OWNER", "active_lock_reason": null, "body": "As per: https://groups.google.com/forum/#!topic/mezzanine-users/7GD4ETP_Oyo\n\nI've reproduced this, not sure what the cause is.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1565/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1565/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1513", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1513/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1513/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1513/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/1513", "id": 127349624, "node_id": "MDU6SXNzdWUxMjczNDk2MjQ=", "number": 1513, "title": "Non-Django fields break field injection", "user": {"login": "jerivas", "id": 2391102, "node_id": "MDQ6VXNlcjIzOTExMDI=", "avatar_url": "https://avatars.githubusercontent.com/u/2391102?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jerivas", "html_url": "https://github.com/jerivas", "followers_url": "https://api.github.com/users/jerivas/followers", "following_url": "https://api.github.com/users/jerivas/following{/other_user}", "gists_url": "https://api.github.com/users/jerivas/gists{/gist_id}", "starred_url": "https://api.github.com/users/jerivas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jerivas/subscriptions", "organizations_url": "https://api.github.com/users/jerivas/orgs", "repos_url": "https://api.github.com/users/jerivas/repos", "events_url": "https://api.github.com/users/jerivas/events{/privacy}", "received_events_url": "https://api.github.com/users/jerivas/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 23, "created_at": "2016-01-19T02:19:53Z", "updated_at": "2017-05-11T09:14:21Z", "closed_at": "2016-05-31T02:51:52Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "This is with Mezzanine 4.1 and Django 1.9.\n\nFirst, I tried to inject a non-built-in field (like one of Mezzanine's):\n\n``` python\nEXTRA_MODEL_FIELDS = (\n    (\n        \"mezzanine.pages.models.Page.featured_image\",\n        \"mezzanine.core.fields.FileField\",\n        (\"Featured Image\",),\n        {\"format\": \"Image\", \"blank\": True,\n         \"upload_to\": \"pages/featured-images\",\n         \"help_text\": \"Image displayed at the top of this page\"},\n    ),\n)\n```\n\nThen, I tried to create the migration: `python manage.py makemigrations pages`\nI got this traceback:\n\n```\nTraceback (most recent call last):\n  File \"manage.py\", line 14, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 353, in execute_from_command_line\n    utility.execute()\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 327, in execute\n    django.setup()\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/registry.py\", line 85, in populate\n    app_config = AppConfig.create(entry)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/config.py\", line 90, in create\n    module = import_module(entry)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/boot/__init__.py\", line 82, in <module>\n    fields = parse_extra_model_fields(getattr(settings, \"EXTRA_MODEL_FIELDS\", []))\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/boot/__init__.py\", line 70, in parse_extra_model_fields\n    field_class = import_field(entry[1])\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/boot/__init__.py\", line 53, in import_field\n    return import_dotted_path(fully_qualified)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/utils/importing.py\", line 23, in import_dotted_path\n    module = import_module(module_path)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/core/fields.py\", line 127, in <module>\n    settings.PACKAGE_NAME_FILEBROWSER)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/mezzanine/utils/importing.py\", line 23, in import_dotted_path\n    module = import_module(module_path)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/filebrowser_safe/fields.py\", line 17, in <module>\n    from filebrowser_safe.base import FileObject\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/filebrowser_safe/base.py\", line 22, in <module>\n    from filebrowser_safe.functions import get_file_type, path_strip, get_directory\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/filebrowser_safe/functions.py\", line 16, in <module>\n    from django.contrib.sites.models import Site\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/contrib/sites/models.py\", line 83, in <module>\n    class Site(models.Model):\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/db/models/base.py\", line 94, in __new__\n    app_config = apps.get_containing_app_config(module)\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/registry.py\", line 239, in get_containing_app_config\n    self.check_apps_ready()\n  File \"/home/jerivas/.virtualenvs/derpa/local/lib/python2.7/site-packages/django/apps/registry.py\", line 124, in check_apps_ready\n    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\ndjango.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n```\n\nImporting one of Django's own fields, like `IntegerField` does not cause the error.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1513/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1513/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1438", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1438/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1438/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1438/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/1438", "id": 112530242, "node_id": "MDU6SXNzdWUxMTI1MzAyNDI=", "number": 1438, "title": "Returns same comment form for different model when requesting from same template.", "user": {"login": "sonus21", "id": 11817278, "node_id": "MDQ6VXNlcjExODE3Mjc4", "avatar_url": "https://avatars.githubusercontent.com/u/11817278?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sonus21", "html_url": "https://github.com/sonus21", "followers_url": "https://api.github.com/users/sonus21/followers", "following_url": "https://api.github.com/users/sonus21/following{/other_user}", "gists_url": "https://api.github.com/users/sonus21/gists{/gist_id}", "starred_url": "https://api.github.com/users/sonus21/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sonus21/subscriptions", "organizations_url": "https://api.github.com/users/sonus21/orgs", "repos_url": "https://api.github.com/users/sonus21/repos", "events_url": "https://api.github.com/users/sonus21/events{/privacy}", "received_events_url": "https://api.github.com/users/sonus21/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-10-21T07:52:15Z", "updated_at": "2016-10-04T21:59:54Z", "closed_at": "2016-07-24T12:58:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "This error occurs when we  request for comments for more than one models from same template.\nUse case :\nLet's initially we request for comment for model Question in the same context again request for comment for Answer model then it returns same form since try catch statement bypasses update of form.\n\nCode from  /mezzanine/generic/templatetags/comment_tags.py\n\n``` python\ndef comments_for(context, obj):\n...\n26    try:\n27        context[\"posted_comment_form\"]\n28    except KeyError:\n29        context[\"posted_comment_form\"] = form\n30    context[\"unposted_comment_form\"] = form\n31    ...\n```\n\nError at line number 26.\nSmall fixed for this.\nReplace try catch block with below code.\n\n``` python\nif context.get(\"posted_comment_form\") is None or \\\n                    context.get(\"posted_comment_form\") != form:\n        context[\"posted_comment_form\"] = form\n        context[\"unposted_comment_form\"] = form \n```\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1438/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1438/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1399", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1399/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1399/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1399/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/1399", "id": 104831648, "node_id": "MDU6SXNzdWUxMDQ4MzE2NDg=", "number": 1399, "title": "FORMS_USE_HTML5 causes a migration", "user": {"login": "jerivas", "id": 2391102, "node_id": "MDQ6VXNlcjIzOTExMDI=", "avatar_url": "https://avatars.githubusercontent.com/u/2391102?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jerivas", "html_url": "https://github.com/jerivas", "followers_url": "https://api.github.com/users/jerivas/followers", "following_url": "https://api.github.com/users/jerivas/following{/other_user}", "gists_url": "https://api.github.com/users/jerivas/gists{/gist_id}", "starred_url": "https://api.github.com/users/jerivas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jerivas/subscriptions", "organizations_url": "https://api.github.com/users/jerivas/orgs", "repos_url": "https://api.github.com/users/jerivas/repos", "events_url": "https://api.github.com/users/jerivas/events{/privacy}", "received_events_url": "https://api.github.com/users/jerivas/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2015-09-04T05:18:36Z", "updated_at": "2015-10-28T03:27:31Z", "closed_at": "2015-10-28T03:27:31Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "Setting `FORMS_USE_HTML5 = True` will trigger a migration, because the `editable` attribute for the placeholder field in [models.py](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/forms/models.py#L68) depends on it.\n\nIt looks like the purpose behind the conditional `editable` is to easily show/hide the placeholder in the `Field` inline admin. Is that correct, or am I missing something?\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1399/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1399/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1396", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1396/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1396/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1396/events", "html_url": "https://github.com/stephenmcd/mezzanine/pull/1396", "id": 103942426, "node_id": "MDExOlB1bGxSZXF1ZXN0NDM3MTkyMDM=", "number": 1396, "title": "re-send class_prepared signal for self-referenced ForeignKeys", "user": {"login": "ZeroXn", "id": 13802767, "node_id": "MDQ6VXNlcjEzODAyNzY3", "avatar_url": "https://avatars.githubusercontent.com/u/13802767?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ZeroXn", "html_url": "https://github.com/ZeroXn", "followers_url": "https://api.github.com/users/ZeroXn/followers", "following_url": "https://api.github.com/users/ZeroXn/following{/other_user}", "gists_url": "https://api.github.com/users/ZeroXn/gists{/gist_id}", "starred_url": "https://api.github.com/users/ZeroXn/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ZeroXn/subscriptions", "organizations_url": "https://api.github.com/users/ZeroXn/orgs", "repos_url": "https://api.github.com/users/ZeroXn/repos", "events_url": "https://api.github.com/users/ZeroXn/events{/privacy}", "received_events_url": "https://api.github.com/users/ZeroXn/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2015-08-30T19:52:25Z", "updated_at": "2016-05-13T21:39:28Z", "closed_at": "2015-12-08T23:21:54Z", "author_association": "NONE", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/pulls/1396", "html_url": "https://github.com/stephenmcd/mezzanine/pull/1396", "diff_url": "https://github.com/stephenmcd/mezzanine/pull/1396.diff", "patch_url": "https://github.com/stephenmcd/mezzanine/pull/1396.patch", "merged_at": null}, "body": "pr for issue #1395\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1396/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/1396/timeline", "performed_via_github_app": null, "state_reason": null}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/871", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/871/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/871/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/871/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/871", "id": 24883935, "node_id": "MDU6SXNzdWUyNDg4MzkzNQ==", "number": 871, "title": "Migrations broken in Django 1.4", "user": {"login": "rockymeza", "id": 21784, "node_id": "MDQ6VXNlcjIxNzg0", "avatar_url": "https://avatars.githubusercontent.com/u/21784?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rockymeza", "html_url": "https://github.com/rockymeza", "followers_url": "https://api.github.com/users/rockymeza/followers", "following_url": "https://api.github.com/users/rockymeza/following{/other_user}", "gists_url": "https://api.github.com/users/rockymeza/gists{/gist_id}", "starred_url": "https://api.github.com/users/rockymeza/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rockymeza/subscriptions", "organizations_url": "https://api.github.com/users/rockymeza/orgs", "repos_url": "https://api.github.com/users/rockymeza/repos", "events_url": "https://api.github.com/users/rockymeza/events{/privacy}", "received_events_url": "https://api.github.com/users/rockymeza/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2013-12-30T13:35:41Z", "updated_at": "2014-03-17T20:59:57Z", "closed_at": "2014-03-17T20:59:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "Related to my comment here: https://github.com/stephenmcd/mezzanine/commit/7d013583d82341694a982f1de33b0d035297c967#commitcomment-4955436\n\nAt first I only had problems with 1.5.1, and I thought that it didn't really matter because 1.5.1 is not the latest version in the 1.5.x series, but this commit (and the one that fixes it) also breaks compatibility with 1.4.10 as well.  At some point, there is some code in South that calls [this function](https://github.com/django/django/blob/1.4.10/django/db/models/fields/related.py#L1117) which calls the `type` built-in function which requires a `str` instead of a `unicode` (in Python 2).  This may or may not be a regression in Django, I don't know, but also I think that the unicode_literals import here could be taken away.\n\nHere are my test failures where I found this out:\n- https://travis-ci.org/fusionbox/django-widgy/jobs/16127777 - I saw that this was fixed in Django 1.5.2 so I changed the travis configuration to install all of the latest versions of 1.4, 1.5, and 1.6\n- https://travis-ci.org/fusionbox/django-widgy/jobs/16138826 - This wasn't failing in 1.4.5 which is also super confusing.\n\nAs of now, the tests are still running, so I don't know everything, but it seems like 1.5.latest and 1.6.latest pass where 1.4.latest fails.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/871/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/871/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/858", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/858/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/858/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/858/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/858", "id": 24525809, "node_id": "MDU6SXNzdWUyNDUyNTgwOQ==", "number": 858, "title": "Random test failure against Python 3.3 in mezzanine.conf", "user": {"login": "stephenmcd", "id": 116385, "node_id": "MDQ6VXNlcjExNjM4NQ==", "avatar_url": "https://avatars.githubusercontent.com/u/116385?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stephenmcd", "html_url": "https://github.com/stephenmcd", "followers_url": "https://api.github.com/users/stephenmcd/followers", "following_url": "https://api.github.com/users/stephenmcd/following{/other_user}", "gists_url": "https://api.github.com/users/stephenmcd/gists{/gist_id}", "starred_url": "https://api.github.com/users/stephenmcd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stephenmcd/subscriptions", "organizations_url": "https://api.github.com/users/stephenmcd/orgs", "repos_url": "https://api.github.com/users/stephenmcd/repos", "events_url": "https://api.github.com/users/stephenmcd/events{/privacy}", "received_events_url": "https://api.github.com/users/stephenmcd/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2013-12-18T23:10:58Z", "updated_at": "2014-11-24T09:40:00Z", "closed_at": "2014-11-24T09:40:00Z", "author_association": "OWNER", "active_lock_reason": null, "body": "This occurs once every dozen or so pushes to the repo:\n\nhttps://travis-ci.org/stephenmcd/mezzanine/jobs/15674182\n\nI've also had it occur locally, but re-running the tests again without any changes doesn't produce the same results, and all tests pass.\n\nOnly seems to occur with Python 3.3 - no idea what's happening, but it's really annoying.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/858/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/858/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/594", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/594/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/594/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/594/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/594", "id": 11779711, "node_id": "MDU6SXNzdWUxMTc3OTcxMQ==", "number": 594, "title": "Admin header covers content when a lot of apps are installed", "user": {"login": "gavinwahl", "id": 421710, "node_id": "MDQ6VXNlcjQyMTcxMA==", "avatar_url": "https://avatars.githubusercontent.com/u/421710?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gavinwahl", "html_url": "https://github.com/gavinwahl", "followers_url": "https://api.github.com/users/gavinwahl/followers", "following_url": "https://api.github.com/users/gavinwahl/following{/other_user}", "gists_url": "https://api.github.com/users/gavinwahl/gists{/gist_id}", "starred_url": "https://api.github.com/users/gavinwahl/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gavinwahl/subscriptions", "organizations_url": "https://api.github.com/users/gavinwahl/orgs", "repos_url": "https://api.github.com/users/gavinwahl/repos", "events_url": "https://api.github.com/users/gavinwahl/events{/privacy}", "received_events_url": "https://api.github.com/users/gavinwahl/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-03-07T21:21:56Z", "updated_at": "2014-03-18T11:15:42Z", "closed_at": "2014-03-18T11:15:42Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "When many apps are installed, the admin header takes up too much space and starts to cover the content:\n\n![image](https://f.cloud.github.com/assets/421710/234121/42b4e20a-876a-11e2-85f9-15797a6b77cf.png)\n\nI am scrolled all the way to the top of the window, but the 'Dashboard' h1 is covered. It also covers success messages, etc.\n\nPS: I'm not sure if this is grappelli or mezzanine, sorry if it's in the wrong place.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/594/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/594/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/535", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/535/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/535/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/535/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/535", "id": 10387302, "node_id": "MDU6SXNzdWUxMDM4NzMwMg==", "number": 535, "title": "django.contrib.redirects does not work with Mezzanine's multi site handling", "user": {"login": "joshcartme", "id": 764456, "node_id": "MDQ6VXNlcjc2NDQ1Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/764456?v=4", "gravatar_id": "", "url": "https://api.github.com/users/joshcartme", "html_url": "https://github.com/joshcartme", "followers_url": "https://api.github.com/users/joshcartme/followers", "following_url": "https://api.github.com/users/joshcartme/following{/other_user}", "gists_url": "https://api.github.com/users/joshcartme/gists{/gist_id}", "starred_url": "https://api.github.com/users/joshcartme/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/joshcartme/subscriptions", "organizations_url": "https://api.github.com/users/joshcartme/orgs", "repos_url": "https://api.github.com/users/joshcartme/repos", "events_url": "https://api.github.com/users/joshcartme/events{/privacy}", "received_events_url": "https://api.github.com/users/joshcartme/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2013-01-28T18:54:51Z", "updated_at": "2013-04-09T12:49:59Z", "closed_at": "2013-04-09T12:49:59Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "The RedirectFallbackMiddleware uses django's get_current_site which will return the SITE_ID in a project's settings if it is present.  Because of this redirects only work on the first site in a project.\n\nA fix would be to rewrite the RedirectFallbackMiddleware using mezzanine's current_site_id rather than django's get_current_site.\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/535/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/535/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/530", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/530/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/530/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/530/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/530", "id": 10065383, "node_id": "MDU6SXNzdWUxMDA2NTM4Mw==", "number": 530, "title": "filebrowser_safe does not work with Amazon S3 (and presumably other services of the same kind)", "user": {"login": "jonatansberg", "id": 58557, "node_id": "MDQ6VXNlcjU4NTU3", "avatar_url": "https://avatars.githubusercontent.com/u/58557?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jonatansberg", "html_url": "https://github.com/jonatansberg", "followers_url": "https://api.github.com/users/jonatansberg/followers", "following_url": "https://api.github.com/users/jonatansberg/following{/other_user}", "gists_url": "https://api.github.com/users/jonatansberg/gists{/gist_id}", "starred_url": "https://api.github.com/users/jonatansberg/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jonatansberg/subscriptions", "organizations_url": "https://api.github.com/users/jonatansberg/orgs", "repos_url": "https://api.github.com/users/jonatansberg/repos", "events_url": "https://api.github.com/users/jonatansberg/events{/privacy}", "received_events_url": "https://api.github.com/users/jonatansberg/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 21, "created_at": "2013-01-17T16:49:29Z", "updated_at": "2016-01-14T15:45:26Z", "closed_at": "2014-02-05T00:25:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "Trying to open the Media Library fails with the following exception when assets are hosted externally (in this case using django-storages on S3): \n\n```\nStacktrace (most recent call last):\n  File \"mezzanine/pages/middleware.py\", line 45, in process_view\n    return view_func(request, *view_args, **view_kwargs)\n  File \"filebrowser_safe/views.py\", line 76, in browse\n    raise ImproperlyConfigured, _(\"Error finding Upload-Folder. Maybe it does not exist?\")\n```\n\n**This is a major issue when running Mezzanine on a PaaS like Heroku where persistent file system access is limited or completely unavailable.**\n\nThe issue has already been discussed throughly here: \nhttps://groups.google.com/d/topic/mezzanine-users/kjsAw6WFqMY/discussion\nand here: https://github.com/sehmaschine/django-filebrowser/issues/40\n\nThere is already a fix in the upstream version of django-filwbrowser, although some other minor issues with thumbnail generation still remain.\n\nIf the fix cannot easily be incorporated in the existing fork, maybe it's time to consider abandoning the *_safe-forks and use the newer versions of grappelli and filebrowser instead. Doing so would have the added benefit of \n- Not having to maintain these packages separately and instead focus on the core of Mezzanine, \n- Maybe fix some existing issues (I'm thinking #62)\n- Gaining access to the progress and other improvements made since forking. [Grappelli](http://www.grappelliproject.com/) is looking really good now...\n\nKeep up the good work!\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/530/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/530/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/526", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/526/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/526/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/526/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/526", "id": 9960133, "node_id": "MDU6SXNzdWU5OTYwMTMz", "number": 526, "title": "Fields with default values cause Dynamic Inlines to break.", "user": {"login": "stephenmcd", "id": 116385, "node_id": "MDQ6VXNlcjExNjM4NQ==", "avatar_url": "https://avatars.githubusercontent.com/u/116385?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stephenmcd", "html_url": "https://github.com/stephenmcd", "followers_url": "https://api.github.com/users/stephenmcd/followers", "following_url": "https://api.github.com/users/stephenmcd/following{/other_user}", "gists_url": "https://api.github.com/users/stephenmcd/gists{/gist_id}", "starred_url": "https://api.github.com/users/stephenmcd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stephenmcd/subscriptions", "organizations_url": "https://api.github.com/users/stephenmcd/orgs", "repos_url": "https://api.github.com/users/stephenmcd/repos", "events_url": "https://api.github.com/users/stephenmcd/events{/privacy}", "received_events_url": "https://api.github.com/users/stephenmcd/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2013-01-14T22:22:29Z", "updated_at": "2013-01-19T02:54:10Z", "closed_at": "2013-01-19T02:54:10Z", "author_association": "OWNER", "active_lock_reason": null, "body": "Default value is put into the hidden inlines, and validation is triggered with a default value when it shouldn't be.\n\nhttps://groups.google.com/group/mezzanine-users/browse_thread/thread/e0504bedfcc27e5c\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/526/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/526/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/413", "repository_url": "https://api.github.com/repos/stephenmcd/mezzanine", "labels_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/413/labels{/name}", "comments_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/413/comments", "events_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/413/events", "html_url": "https://github.com/stephenmcd/mezzanine/issues/413", "id": 7168427, "node_id": "MDU6SXNzdWU3MTY4NDI3", "number": 413, "title": "page_menu tag needs has_children_in_menu helpers", "user": {"login": "stephenmcd", "id": 116385, "node_id": "MDQ6VXNlcjExNjM4NQ==", "avatar_url": "https://avatars.githubusercontent.com/u/116385?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stephenmcd", "html_url": "https://github.com/stephenmcd", "followers_url": "https://api.github.com/users/stephenmcd/followers", "following_url": "https://api.github.com/users/stephenmcd/following{/other_user}", "gists_url": "https://api.github.com/users/stephenmcd/gists{/gist_id}", "starred_url": "https://api.github.com/users/stephenmcd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stephenmcd/subscriptions", "organizations_url": "https://api.github.com/users/stephenmcd/orgs", "repos_url": "https://api.github.com/users/stephenmcd/repos", "events_url": "https://api.github.com/users/stephenmcd/events{/privacy}", "received_events_url": "https://api.github.com/users/stephenmcd/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 14971355, "node_id": "MDU6TGFiZWwxNDk3MTM1NQ==", "url": "https://api.github.com/repos/stephenmcd/mezzanine/labels/bug", "name": "bug", "color": "73D5ED", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2012-09-27T00:38:08Z", "updated_at": "2012-10-01T06:47:13Z", "closed_at": "2012-10-01T06:47:13Z", "author_association": "OWNER", "active_lock_reason": null, "body": "The current has_children helper for pages in the page_menu tag doesn't accurately reflect whether the page has children in the context of the current menu being rendered.\n\nDiscussed here:\n\nhttps://groups.google.com/group/mezzanine-users/browse_thread/thread/132c096e70893e26#\n", "reactions": {"url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/413/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/stephenmcd/mezzanine/issues/413/timeline", "performed_via_github_app": null, "state_reason": "completed"}]