[{"url": "https://api.github.com/repos/zappa/Zappa/issues/1201", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/1201/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/1201/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/1201/events", "html_url": "https://github.com/zappa/Zappa/issues/1201", "id": 1471512992, "node_id": "I_kwDOEKt2zM5XtYGg", "number": 1201, "title": "FileNotFoundError in running_in_docker", "user": {"login": "hassa", "id": 425229, "node_id": "MDQ6VXNlcjQyNTIyOQ==", "avatar_url": "https://avatars.githubusercontent.com/u/425229?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hassa", "html_url": "https://github.com/hassa", "followers_url": "https://api.github.com/users/hassa/followers", "following_url": "https://api.github.com/users/hassa/following{/other_user}", "gists_url": "https://api.github.com/users/hassa/gists{/gist_id}", "starred_url": "https://api.github.com/users/hassa/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hassa/subscriptions", "organizations_url": "https://api.github.com/users/hassa/orgs", "repos_url": "https://api.github.com/users/hassa/repos", "events_url": "https://api.github.com/users/hassa/events{/privacy}", "received_events_url": "https://api.github.com/users/hassa/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757009699, "node_id": "MDU6TGFiZWwyNzU3MDA5Njk5", "url": "https://api.github.com/repos/zappa/Zappa/labels/has-pr", "name": "has-pr", "color": "b3dd6e", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2022-12-01T15:26:58Z", "updated_at": "2022-12-05T11:45:48Z", "closed_at": "2022-12-05T11:45:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "<!--- Provide a general summary of the issue in the Title above -->\r\n## Context\r\n<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->\r\n<!--- Also, please make sure that you are running Zappa _from a virtual environment_ and are using Python 3.7/3.8/3.9 -->\r\n\r\nIn `running_in_docker` if there is no `/proc/1/cgroup`, like on OSX for example, a FileNotFoundError is raised and zappa can't be imported.\r\n\r\nWe do some stuff with SQS and zappa's asynchronous tasks so we import zappa even during dev.\r\n\r\n## Expected Behavior\r\n<!--- Tell us what should happen -->\r\nFileNotFoundError should be caught and running_in_docker should return False.\r\n\r\n## Actual Behavior\r\n<!--- Tell us what happens instead -->\r\nA FileNotFoundError is raised.\r\n\r\n## Possible Fix\r\n<!--- Not obligatory, but suggest a fix or reason for the bug -->\r\nFileNotFoundError should be caught and running_in_docker should return False.\r\n\r\n## Steps to Reproduce\r\n<!--- Provide a link to a live example, or an unambiguous set of steps to -->\r\n<!--- reproduce this bug include code to reproduce, if relevant -->\r\n1. Be on OSX\r\n2. import zappa\r\n3.\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: 0.56.0\r\n* Operating System and Python version: OSX 12.6, Python 3.9 and 3.11.0\r\n* The output of `pip freeze`:\r\n* Link to your project (optional):\r\n* Your `zappa_settings.json`: \r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/1201/reactions", "total_count": 1, "+1": 1, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/1201/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/1132", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/1132/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/1132/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/1132/events", "html_url": "https://github.com/zappa/Zappa/issues/1132", "id": 1230778941, "node_id": "I_kwDOEKt2zM5JXDI9", "number": 1132, "title": "Not recognizing virtaulenv created with pyenv.", "user": {"login": "iml1111", "id": 29897277, "node_id": "MDQ6VXNlcjI5ODk3Mjc3", "avatar_url": "https://avatars.githubusercontent.com/u/29897277?v=4", "gravatar_id": "", "url": "https://api.github.com/users/iml1111", "html_url": "https://github.com/iml1111", "followers_url": "https://api.github.com/users/iml1111/followers", "following_url": "https://api.github.com/users/iml1111/following{/other_user}", "gists_url": "https://api.github.com/users/iml1111/gists{/gist_id}", "starred_url": "https://api.github.com/users/iml1111/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/iml1111/subscriptions", "organizations_url": "https://api.github.com/users/iml1111/orgs", "repos_url": "https://api.github.com/users/iml1111/repos", "events_url": "https://api.github.com/users/iml1111/events{/privacy}", "received_events_url": "https://api.github.com/users/iml1111/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757009804, "node_id": "MDU6TGFiZWwyNzU3MDA5ODA0", "url": "https://api.github.com/repos/zappa/Zappa/labels/needs-release", "name": "needs-release", "color": "33b205", "default": false, "description": null}, {"id": 4332369946, "node_id": "LA_kwDOEKt2zM8AAAABAjq4Gg", "url": "https://api.github.com/repos/zappa/Zappa/labels/next-release-candidate", "name": "next-release-candidate", "color": "5319e7", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": {"login": "iml1111", "id": 29897277, "node_id": "MDQ6VXNlcjI5ODk3Mjc3", "avatar_url": "https://avatars.githubusercontent.com/u/29897277?v=4", "gravatar_id": "", "url": "https://api.github.com/users/iml1111", "html_url": "https://github.com/iml1111", "followers_url": "https://api.github.com/users/iml1111/followers", "following_url": "https://api.github.com/users/iml1111/following{/other_user}", "gists_url": "https://api.github.com/users/iml1111/gists{/gist_id}", "starred_url": "https://api.github.com/users/iml1111/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/iml1111/subscriptions", "organizations_url": "https://api.github.com/users/iml1111/orgs", "repos_url": "https://api.github.com/users/iml1111/repos", "events_url": "https://api.github.com/users/iml1111/events{/privacy}", "received_events_url": "https://api.github.com/users/iml1111/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "iml1111", "id": 29897277, "node_id": "MDQ6VXNlcjI5ODk3Mjc3", "avatar_url": "https://avatars.githubusercontent.com/u/29897277?v=4", "gravatar_id": "", "url": "https://api.github.com/users/iml1111", "html_url": "https://github.com/iml1111", "followers_url": "https://api.github.com/users/iml1111/followers", "following_url": "https://api.github.com/users/iml1111/following{/other_user}", "gists_url": "https://api.github.com/users/iml1111/gists{/gist_id}", "starred_url": "https://api.github.com/users/iml1111/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/iml1111/subscriptions", "organizations_url": "https://api.github.com/users/iml1111/orgs", "repos_url": "https://api.github.com/users/iml1111/repos", "events_url": "https://api.github.com/users/iml1111/events{/privacy}", "received_events_url": "https://api.github.com/users/iml1111/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2022-05-10T08:08:11Z", "updated_at": "2022-12-01T10:02:40Z", "closed_at": "2022-12-01T10:02:40Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "<!--- Provide a general summary of the issue in the Title above -->\r\n## Context\r\nIf .python-version does not exist in the current path, the virtual environment of pyenv is not recognized.\r\n<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->\r\n<!--- Also, please make sure that you are running Zappa _from a virtual environment_ and are using Python 3.6/3.7/3.8 -->\r\n\r\n## Expected Behavior\r\n<!--- Tell us what should happen -->\r\n```shell\r\n> zappa update dev\r\nCalling update for stage dev..\r\nDownloading and installing dependencies..\r\n...\r\n```\r\n\r\n## Actual Behavior\r\n```shell\r\n# .python-version is not in that path, but pyenv works correctly.\r\n> pwd\r\n/Users/username/Documents/GitHub/myenv/myproject\r\n> pyenv versions\r\n* my-env (set by /Users/username/Documents/GitHub/my-env/.python-version)\r\n...\r\n\r\n> zappa update dev\r\nCalling update for stage dev..\r\nError: Zappa requires an active virtual environment!\r\nLearn more about virtual environments here: http://docs.python-guide.org/en/latest/dev/virtualenvs/\r\n```\r\n<!--- Tell us what happens instead -->\r\n\r\n## Possible Fix\r\nIn addition to detecting the .python-version file in the current path, you can check the current virtual environment by using the `pyenv version` command.\r\n<!--- Not obligatory, but suggest a fix or reason for the bug -->\r\n\r\n## Steps to Reproduce\r\n<!--- Provide a link to a live example, or an unambiguous set of steps to -->\r\n<!--- reproduce this bug include code to reproduce, if relevant -->\r\n1.\r\n2.\r\n3.\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: 0.54.1\r\n* Operating System and Python version: 3.9.12\r\n* The output of `pip freeze`:\r\n```\r\nargcomplete==2.0.0\r\nawscli==1.22.87\r\nboto3==1.21.32\r\nbotocore==1.24.32\r\ncertifi==2021.10.8\r\ncfn-flip==1.3.0\r\ncharset-normalizer==2.0.12\r\nclick==8.1.2\r\ncolorama==0.4.3\r\ndocutils==0.15.2\r\ndurationpy==0.5\r\nFaker==13.3.4\r\nFlask==2.1.1\r\nflask-validation-extended==0.1.7\r\nfuture==0.18.2\r\nhjson==3.0.2\r\nidna==3.3\r\nimportlib-metadata==4.11.3\r\nitsdangerous==2.1.2\r\nJinja2==3.1.1\r\njmespath==1.0.0\r\nkappa==0.6.0\r\nMarkupSafe==2.1.1\r\nplacebo==0.9.0\r\npyasn1==0.4.8\r\npython-dateutil==2.8.2\r\npython-dotenv==0.20.0\r\npython-slugify==6.1.1\r\nPyYAML==5.4.1\r\nrequests==2.27.1\r\nrsa==4.7.2\r\ns3transfer==0.5.2\r\nsix==1.16.0\r\nslack-sdk==3.15.2\r\ntext-unidecode==1.3\r\ntoml==0.10.2\r\ntqdm==4.64.0\r\ntroposphere==4.0.0\r\nurllib3==1.26.9\r\nWerkzeug==2.1.1\r\nwsgi-request-logger==0.4.6\r\nzappa==0.54.1\r\nzipp==3.8.0\r\n```\r\n* Link to your project (optional): I don't think this is necessary.\r\n* Your `zappa_settings.json`:  I don't think this is necessary.\r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/1132/reactions", "total_count": 2, "+1": 2, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/1132/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/560", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/560/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/560/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/560/events", "html_url": "https://github.com/zappa/Zappa/issues/560", "id": 812596746, "node_id": "MDU6SXNzdWU4MTI1OTY3NDY=", "number": 560, "title": "[Migrated] Pip 10 compatibility issues", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757531216, "node_id": "MDU6TGFiZWwyNzU3NTMxMjE2", "url": "https://api.github.com/repos/zappa/Zappa/labels/upstream", "name": "upstream", "color": "ededed", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2021-02-20T12:22:46Z", "updated_at": "2022-07-16T07:06:39Z", "closed_at": "2022-07-16T07:06:39Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/1478 by [jleclanche](https://github.com/jleclanche)\n\nPip 10 was just released and I'm now getting this with it:\r\n\r\n```pytb\r\n\r\n12:15:05 Traceback (most recent call last):\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py\", line 2610, in handle\r\n12:15:05     sys.exit(cli.handle())\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py\", line 505, in handle\r\n12:15:05     self.dispatch_command(self.command, stage)\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py\", line 549, in dispatch_command\r\n12:15:05     self.update(self.vargs['zip'], self.vargs['no_upload'])\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py\", line 877, in update\r\n12:15:05     self.create_package()\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py\", line 2171, in create_package\r\n12:15:05     disable_progress=self.disable_progress\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/core.py\", line 595, in create_lambda_zip\r\n12:15:05     installed_packages = self.get_installed_packages(site_packages, site_packages_64)\r\n12:15:05   File \"/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/core.py\", line 751, in get_installed_packages\r\n12:15:05     pip.get_installed_distributions()\r\n12:15:05 AttributeError: module 'pip' has no attribute 'get_installed_distributions'\r\n12:15:05 Build step 'Execute shell' marked build as failure\r\n12:15:05 Finished: FAILURE\r\n```\r\n\r\nWorkaround: force install pip==9.0.3.", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/560/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/560/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/525", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/525/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/525/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/525/events", "html_url": "https://github.com/zappa/Zappa/issues/525", "id": 812566050, "node_id": "MDU6SXNzdWU4MTI1NjYwNTA=", "number": 525, "title": "[Migrated] Zappa crashes when running \"zappa\"", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757009777, "node_id": "MDU6TGFiZWwyNzU3MDA5Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/needs-info", "name": "needs-info", "color": "4758ef", "default": false, "description": null}, {"id": 2757132937, "node_id": "MDU6TGFiZWwyNzU3MTMyOTM3", "url": "https://api.github.com/repos/zappa/Zappa/labels/windows", "name": "windows", "color": "ededed", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2021-02-20T09:43:55Z", "updated_at": "2022-07-16T07:16:02Z", "closed_at": "2022-07-16T07:16:02Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/1395 by [cameronk](https://github.com/cameronk)\n\n<!--- Provide a general summary of the issue in the Title above -->\r\n## Context\r\nAfter two days and two different OS', I finally got Zappa working. For about 5 minutes, until I had to reset my virtual env (Zappa was packaging my entire virtual env, including /lib/, which resulted in ~100mb deploy zips.)\r\n\r\nWhen I reinstalled, I now get this:\r\n\r\n```\r\ncamer@DESKTOP-VRG88TF:/mnt/c/Users/camer/Desktop/Development/ryze/content-engine/api$ zappa\r\nOh no! An error occurred! :(\r\n\r\n==============\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/camer/.local/share/virtualenvs/api-GJXpcMFr/lib/python3.6/site-packages/zappa/cli.py\", line 2610, in handle\r\n    sys.exit(cli.handle())\r\n  File \"/home/camer/.local/share/virtualenvs/api-GJXpcMFr/lib/python3.6/site-packages/zappa/cli.py\", line 505, in handle\r\n    self.dispatch_command(self.command, stage)\r\n  File \"/home/camer/.local/share/virtualenvs/api-GJXpcMFr/lib/python3.6/site-packages/zappa/cli.py\", line 520, in dispatch_command\r\n    if not self.vargs['json']:\r\nKeyError: 'json'\r\n\r\n==============\r\n\r\nNeed help? Found a bug? Let us know! :D\r\nFile bug reports on GitHub here: https://github.com/Miserlou/Zappa\r\nAnd join our Slack channel here: https://slack.zappa.io\r\nLove!,\r\n ~ Team Zappa!\r\n```\r\n\r\n## Expected Behavior\r\nZappa should output the usual list of help commands\r\n\r\n## Actual Behavior\r\nZappa breaks\r\n\r\n\r\n## Steps to Reproduce\r\n<!--- Provide a link to a live example, or an unambiguous set of steps to -->\r\n<!--- reproduce this bug include code to reproduce, if relevant -->\r\n1. Create a virtual env with `pipenv` on python 3.6\r\n2. Run `zappa`\r\n3. It breaks\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: 0.45.1\r\n* Operating System and Python version: Python 3.6.3, Ubuntu 16.04.3\r\n* Your `zappa_settings.py`: \r\n```\r\n{\r\n    \"dev\": {\r\n        \"app_function\": \"app.app\",\r\n        \"aws_region\": null,\r\n        \"profile_name\": \"zappa\",\r\n        \"project_name\": \"api\",\r\n        \"runtime\": \"python3.6\",\r\n        \"s3_bucket\": \"zappa-i38d9iob8\"\r\n    }\r\n}\r\n```", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/525/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/525/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/524", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/524/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/524/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/524/events", "html_url": "https://github.com/zappa/Zappa/issues/524", "id": 812566047, "node_id": "MDU6SXNzdWU4MTI1NjYwNDc=", "number": 524, "title": "[Migrated] Zappa crashes during zappa init", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757132937, "node_id": "MDU6TGFiZWwyNzU3MTMyOTM3", "url": "https://api.github.com/repos/zappa/Zappa/labels/windows", "name": "windows", "color": "ededed", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2021-02-20T09:43:54Z", "updated_at": "2022-07-16T07:16:22Z", "closed_at": "2022-07-16T07:16:21Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/1388 by [cameronk](https://github.com/cameronk)\n\n<!--- Provide a general summary of the issue in the Title above -->\r\n## Context\r\nZappa crashes when running `zappa init`, after the step where I name the bucket.\r\n\r\n```\r\n==============\r\n\r\nTraceback (most recent call last):\r\n  File \"c:\\users\\camer\\desktop\\development\\ryze\\content-engine\\api\\env\\lib\\site-packages\\zappa\\cli.py\", line 2610, in handle\r\n    sys.exit(cli.handle())\r\n  File \"c:\\users\\camer\\desktop\\development\\ryze\\content-engine\\api\\env\\lib\\site-packages\\zappa\\cli.py\", line 476, in handle\r\n    self.init()\r\n  File \"c:\\users\\camer\\desktop\\development\\ryze\\content-engine\\api\\env\\lib\\site-packages\\zappa\\cli.py\", line 1604, in init\r\n    matches = detect_flask_apps()\r\n  File \"c:\\users\\camer\\desktop\\development\\ryze\\content-engine\\api\\env\\lib\\site-packages\\zappa\\utilities.py\", line 143, in detect_flask_apps\r\n    lines = f.readlines()\r\n  File \"c:\\users\\camer\\desktop\\development\\ryze\\content-engine\\api\\env\\lib\\encodings\\cp1252.py\", line 23, in decode\r\n    return codecs.charmap_decode(input,self.errors,decoding_table)[0]\r\nUnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 308: character maps to <undefined>\r\n\r\n==============\r\n```\r\n\r\n## Expected Behavior\r\nzappa should initialize\r\n\r\n## Actual Behavior\r\nit crashes\r\n\r\n## Steps to Reproduce\r\n1. create a virtual environment, install zappa\r\n2. run `zappa init`\r\n3. it breaks\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: 0.45.1\r\n* Operating System and Python version: Windows 10, Python 3.6.3\r\n* The output of `pip freeze`: \r\n```\r\nbeautifulsoup4==4.6.0\r\ncertifi==2018.1.18\r\nchardet==3.0.4\r\nclick==6.7\r\ncssselect==1.0.3\r\nfeedfinder2==0.0.4\r\nfeedparser==5.2.1\r\nFlask==0.12.2\r\nFlask-MySQLdb==0.2.0\r\nidna==2.6\r\nitsdangerous==0.24\r\njieba3k==0.35.1\r\nJinja2==2.10\r\nlxml==4.1.1\r\nMarkupSafe==1.0\r\nmysqlclient==1.3.12\r\nnewspaper3k==0.2.6\r\nnltk==3.2.5\r\nPillow==5.0.0\r\npython-dateutil==2.6.1\r\nPyYAML==3.12\r\nrequests==2.18.4\r\nrequests-file==1.4.3\r\nscikit-learn==0.19.1\r\nsix==1.11.0\r\ntldextract==2.2.0\r\nurllib3==1.22\r\nWerkzeug==0.14.1\r\n```\r\n* Link to your project (optional):\r\n* Your `zappa_settings.py`:  I wish I could get this far\r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/524/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/524/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/422", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/422/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/422/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/422/events", "html_url": "https://github.com/zappa/Zappa/issues/422", "id": 812552642, "node_id": "MDU6SXNzdWU4MTI1NTI2NDI=", "number": 422, "title": "[Migrated] s3 zip includes files that should be matched by the `exclude` setting", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757009673, "node_id": "MDU6TGFiZWwyNzU3MDA5Njcz", "url": "https://api.github.com/repos/zappa/Zappa/labels/hacktoberfest", "name": "hacktoberfest", "color": "d93f0b", "default": false, "description": null}, {"id": 2757009699, "node_id": "MDU6TGFiZWwyNzU3MDA5Njk5", "url": "https://api.github.com/repos/zappa/Zappa/labels/has-pr", "name": "has-pr", "color": "b3dd6e", "default": false, "description": null}, {"id": 2757009804, "node_id": "MDU6TGFiZWwyNzU3MDA5ODA0", "url": "https://api.github.com/repos/zappa/Zappa/labels/needs-release", "name": "needs-release", "color": "33b205", "default": false, "description": null}, {"id": 4332369946, "node_id": "LA_kwDOEKt2zM8AAAABAjq4Gg", "url": "https://api.github.com/repos/zappa/Zappa/labels/next-release-candidate", "name": "next-release-candidate", "color": "5319e7", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": {"login": "monkut", "id": 1135529, "node_id": "MDQ6VXNlcjExMzU1Mjk=", "avatar_url": "https://avatars.githubusercontent.com/u/1135529?v=4", "gravatar_id": "", "url": "https://api.github.com/users/monkut", "html_url": "https://github.com/monkut", "followers_url": "https://api.github.com/users/monkut/followers", "following_url": "https://api.github.com/users/monkut/following{/other_user}", "gists_url": "https://api.github.com/users/monkut/gists{/gist_id}", "starred_url": "https://api.github.com/users/monkut/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/monkut/subscriptions", "organizations_url": "https://api.github.com/users/monkut/orgs", "repos_url": "https://api.github.com/users/monkut/repos", "events_url": "https://api.github.com/users/monkut/events{/privacy}", "received_events_url": "https://api.github.com/users/monkut/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "monkut", "id": 1135529, "node_id": "MDQ6VXNlcjExMzU1Mjk=", "avatar_url": "https://avatars.githubusercontent.com/u/1135529?v=4", "gravatar_id": "", "url": "https://api.github.com/users/monkut", "html_url": "https://github.com/monkut", "followers_url": "https://api.github.com/users/monkut/followers", "following_url": "https://api.github.com/users/monkut/following{/other_user}", "gists_url": "https://api.github.com/users/monkut/gists{/gist_id}", "starred_url": "https://api.github.com/users/monkut/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/monkut/subscriptions", "organizations_url": "https://api.github.com/users/monkut/orgs", "repos_url": "https://api.github.com/users/monkut/repos", "events_url": "https://api.github.com/users/monkut/events{/privacy}", "received_events_url": "https://api.github.com/users/monkut/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2021-02-20T08:32:43Z", "updated_at": "2022-12-01T10:06:19Z", "closed_at": "2022-12-01T10:06:19Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/1083 by [waynr](https://github.com/waynr)\n\n<!--- Provide a general summary of the issue in the Title above -->\r\n## Context\r\n<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->\r\n<!--- Also, please make sure that you are running Zappa _from a virtual environment_ and are using Python 2.7 -->\r\nI am attempting to deploy a Flask app as an AWS Lambda + API Gateway but pretty am consistently seeing way too many files I don't want in the zip produced by the `package` command. The specific files I want to include are all those found in the `.tox` directory of my git repo.\r\n\r\nMy working directory has a file named `zappa_settings.json` with the following contents:\r\n```\r\n{\r\n    \"pytest\": {\r\n        \"app_function\": \"autoapp.app\",\r\n        \"aws_region\": \"us-west-2\",\r\n        \"exclude\": [\".tox/*\", \"tmp/*\"],\r\n        \"profile_name\": \"default\",\r\n        \"s3_bucket\": \"zappa-wnwh277zd\",\r\n        \"slim_handler\": \"true\",\r\n    }\r\n}\r\n```\r\n\r\nI happen to be using ZappaCLI programmatically for some pytest fixtures I am working on, but the problem is also reproducible when running `zappa package pytest`\r\n\r\nI chose to use `.tox/*` because that is how I see it done in zappa itself with `.git/*`:\r\nhttps://github.com/Miserlou/Zappa/blob/master/zappa/core.py#L174\r\n\r\nAnd I can confirm that `.git/*` does the trick since I don't see any paths in the resulting archive starting with `.git/`\r\n\r\n## Expected Behavior\r\n<!--- Tell us what should happen -->\r\nI shouldn't see any paths starting with `.tox/` in the archive that zappa produces. \r\n\r\n## Actual Behavior\r\n<!--- Tell us what happens instead -->\r\nI see a metric shit ton of paths starting with `.tox/` in the archive that zappa produces.\r\n\r\n## Possible Fix\r\n<!--- Not obligatory, but suggest a fix or reason for the bug -->\r\nFor my specific use case it will probably make sense to add `.tox/*` to `zappa.core.ZIP_EXCLUDES`.\r\n\r\n## Steps to Reproduce\r\n* make a bunch of tox environments in a project\r\n* add `.tox/*` to the `exclude` list in your zappa settings\r\n* run `zappa package <envname>`\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: `o.43.2`\r\n* Operating System and Python version: `Debian 9` and `Python 3.6.2`\r\n* The output of `pip freeze`:\r\n```\r\nargcomplete==1.8.2\r\nbase58==0.2.4\r\nbeautifulsoup4==4.6.0\r\nboto3==1.4.5\r\nbotocore==1.5.40\r\nbumpversion==0.5.3\r\ncached-property==1.3.0\r\ncertifi==2017.7.27.1\r\nchardet==3.0.4\r\nclick==6.7\r\ncolorama==0.3.9\r\ndecorator==4.1.2\r\ndocker==2.5.1\r\ndocker-compose==1.15.0\r\ndocker-pycreds==0.2.1\r\ndockerpty==0.4.1\r\ndocopt==0.6.2\r\ndocutils==0.14\r\ndurationpy==0.5\r\nflake8==2.6.0\r\nFlask==0.12.2\r\nflask-dynamo==0.1.1\r\nfuture==0.16.0\r\nfutures==3.1.1\r\nhjson==3.0.0\r\nidna==2.6\r\nipython==6.1.0\r\nipython-genutils==0.2.0\r\nitsdangerous==0.24\r\njedi==0.10.2\r\nJinja2==2.9.6\r\njmespath==0.9.3\r\njsonschema==2.6.0\r\nkappa==0.6.0\r\nlambda-packages==0.16.1\r\nMarkupSafe==1.0\r\nmccabe==0.5.3\r\npexpect==4.2.1\r\npickleshare==0.7.4\r\npkg-resources==0.0.0\r\nplacebo==0.8.1\r\npluggy==0.3.1\r\nprompt-toolkit==1.0.15\r\nptyprocess==0.5.2\r\npy==1.4.34\r\npycodestyle==2.0.0\r\npyflakes==1.2.3\r\nPygments==2.2.0\r\npytest==3.1.3\r\npytest-runner==2.11.1\r\npython-dateutil==2.6.1\r\npython-slugify==1.2.4\r\nPyYAML==3.12\r\nrequests==2.18.4\r\ns3transfer==0.1.10\r\nsimplegeneric==0.8.1\r\nsix==1.10.0\r\ntexttable==0.8.8\r\ntoml==0.9.2\r\ntox==2.3.1\r\ntqdm==4.15.0\r\ntraitlets==4.3.2\r\ntroposphere==1.9.5\r\nUnidecode==0.4.21\r\nurllib3==1.22\r\nvirtualenv==15.1.0\r\nwaitress==1.0.2\r\nwcwidth==0.1.7\r\nWebOb==1.7.3\r\nwebsocket-client==0.44.0\r\nWebTest==2.0.28\r\nWerkzeug==0.12\r\nwsgi-request-logger==0.4.6\r\nzappa==0.43.2\r\n```\r\n* Link to your project (optional):\r\n* Your `zappa_settings.py`: \r\n```\r\n{\r\n    \"pytest\": {\r\n        \"app_function\": \"autoapp.app\",\r\n        \"aws_region\": \"us-west-2\",\r\n        \"exclude\": [\".tox/*\", \"tmp/*\"],\r\n        \"profile_name\": \"default\",\r\n        \"s3_bucket\": \"zappa-wnwh277zd\",\r\n        \"slim_handler\": \"true\",\r\n    }\r\n}\r\n```", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/422/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/422/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/302", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/302/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/302/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/302/events", "html_url": "https://github.com/zappa/Zappa/issues/302", "id": 812551263, "node_id": "MDU6SXNzdWU4MTI1NTEyNjM=", "number": 302, "title": "[Migrated] `zappa package` doesn't include dist-packages", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2204045782, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzgy", "url": "https://api.github.com/repos/zappa/Zappa/labels/help%20wanted", "name": "help wanted", "color": "008672", "default": true, "description": "Extra attention is needed"}, {"id": 2757009579, "node_id": "MDU6TGFiZWwyNzU3MDA5NTc5", "url": "https://api.github.com/repos/zappa/Zappa/labels/aws", "name": "aws", "color": "fbca04", "default": false, "description": null}, {"id": 2757009816, "node_id": "MDU6TGFiZWwyNzU3MDA5ODE2", "url": "https://api.github.com/repos/zappa/Zappa/labels/needs-test", "name": "needs-test", "color": "0fa7af", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-02-20T08:25:23Z", "updated_at": "2021-02-20T16:08:53Z", "closed_at": "2021-02-20T16:08:53Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/905 by [monkeypants](https://github.com/monkeypants)\n\n`zappa --package` bundles site-packages from the virtualenv. But, on some distributions, pip installs stuff into `dist-packages`. So, there is a problem that these platforms (e.g. AMI linux) that they don't include pip-installed packages when they `zappa --package`\r\n\r\n## Context\r\nDo `zappa --package` on with an AMI linux box, or some other platform that does strange things to pip, so it installs stuff into `dist-packages`.\r\n\r\n## Expected Behavior\r\nI would like to see all the stuff from dist-packages in the zappa package, so my thing works the same even if I build it on Amazon Linux.\r\n\r\n## Actual Behavior\r\nThe site-packages is included in the zappa package. The dist-packages are not. The stuff I installed with pip in my virtualenv is not included in the zappa package if I ran it on a wacky OS, and my thing doesn't work because it's requirements are not met.\r\n\r\n## Possible Fix\r\n\r\n * update create_handler_venv in zappa/core.py so it does stuff with dist-packages for the relevant platforms\r\n * update detect_flask_apps and detect_django_settings in zappa/utilities.py so they check dist-packages too\r\n * Is this maybe related to why [/tests/tests.py#L70](https://github.com/Miserlou/Zappa/blob/5641b506090dd3f24e09b0c044c1b47d76f15629/tests/tests.py#L70) is commented out?\r\n \r\n## Steps to Reproduce\r\n1. Make yourself at home in an AWS Linux AMI\r\n2. Create a virtualenv and activate it.\r\n3. `pip install` a bunch of stuff, such as the requirements for you app\r\n4. See for yourself how there is a bunch of stuff installed in dist-packages\r\n5. do `zappa --package`\r\n6. compare the size of the lambda.zip with one made on non-debian distribution (it's smaller, because it doesn't include the packages from your virtualenv)\r\n7. see how the thing fails with unmet dependencies if you deploy it\r\n8. see how the lambda.zip does not contain your requirements\r\n\r\n## Your Environment\r\n* Zappa version used: latest\r\n* Operating System and Python version: Amazon Linux AMI\r\n* The output of `pip freeze`: any\r\n* Link to your project (optional): N/A\r\n* Your `zappa_settings.py`: N/A (I think)\r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/302/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/302/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/297", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/297/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/297/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/297/events", "html_url": "https://github.com/zappa/Zappa/issues/297", "id": 812551249, "node_id": "MDU6SXNzdWU4MTI1NTEyNDk=", "number": 297, "title": "[Migrated] Zappa certify fails on/after waiting for DNS propagation", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757112021, "node_id": "MDU6TGFiZWwyNzU3MTEyMDIx", "url": "https://api.github.com/repos/zappa/Zappa/labels/python3", "name": "python3", "color": "ededed", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-02-20T08:25:19Z", "updated_at": "2021-02-20T16:08:52Z", "closed_at": "2021-02-20T16:08:52Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/887 by [GeoTob](https://github.com/GeoTob)\n\n## Context\r\nRunning zappa 0.42.0 on py3.6, I followed the \"custom domain with LE\" part of the documentation. I got to the \"waiting for DNS propagation\" stage, which after ~45s errors with:\r\n\r\n```\r\nSetting DNS challenge..\r\nWaiting for DNS to propagate..\r\nObject of type 'bytes' is not JSON serializable\r\n```\r\n \r\n## Possible Fix\r\nWhen `letsencrypt._send_signed_request` is called, `keyAuthorization` is passed as bytes and not string.\r\n\r\nThis fixes the issue but is far from elegant:\r\n```py\r\ndef _send_signed_request(url, payload):\r\n    \"\"\"\r\n    Helper function to make signed requests to Boulder\r\n    \"\"\"\r\n\r\n    if 'keyAuthorization' in payload:\r\n        try:\r\n            payload['keyAuthorization'] = payload['keyAuthorization'].decode()\r\n        except AttributeError:\r\n            pass\r\n```\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: 0.42.0\r\n* Operating System and Python version: ubuntu16.04/py3.6\r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/297/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/297/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/246", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/246/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/246/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/246/events", "html_url": "https://github.com/zappa/Zappa/issues/246", "id": 812550914, "node_id": "MDU6SXNzdWU4MTI1NTA5MTQ=", "number": 246, "title": "[Migrated] `zappa package` doesn't include dist-packages", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2204045782, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzgy", "url": "https://api.github.com/repos/zappa/Zappa/labels/help%20wanted", "name": "help wanted", "color": "008672", "default": true, "description": "Extra attention is needed"}, {"id": 2757009579, "node_id": "MDU6TGFiZWwyNzU3MDA5NTc5", "url": "https://api.github.com/repos/zappa/Zappa/labels/aws", "name": "aws", "color": "fbca04", "default": false, "description": null}, {"id": 2757009816, "node_id": "MDU6TGFiZWwyNzU3MDA5ODE2", "url": "https://api.github.com/repos/zappa/Zappa/labels/needs-test", "name": "needs-test", "color": "0fa7af", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-02-20T08:23:42Z", "updated_at": "2021-02-20T16:08:05Z", "closed_at": "2021-02-20T16:08:05Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/905 by [monkeypants](https://github.com/monkeypants)\n\n`zappa --package` bundles site-packages from the virtualenv. But, on some distributions, pip installs stuff into `dist-packages`. So, there is a problem that these platforms (e.g. AMI linux) that they don't include pip-installed packages when they `zappa --package`\r\n\r\n## Context\r\nDo `zappa --package` on with an AMI linux box, or some other platform that does strange things to pip, so it installs stuff into `dist-packages`.\r\n\r\n## Expected Behavior\r\nI would like to see all the stuff from dist-packages in the zappa package, so my thing works the same even if I build it on Amazon Linux.\r\n\r\n## Actual Behavior\r\nThe site-packages is included in the zappa package. The dist-packages are not. The stuff I installed with pip in my virtualenv is not included in the zappa package if I ran it on a wacky OS, and my thing doesn't work because it's requirements are not met.\r\n\r\n## Possible Fix\r\n\r\n * update create_handler_venv in zappa/core.py so it does stuff with dist-packages for the relevant platforms\r\n * update detect_flask_apps and detect_django_settings in zappa/utilities.py so they check dist-packages too\r\n * Is this maybe related to why [/tests/tests.py#L70](https://github.com/Miserlou/Zappa/blob/5641b506090dd3f24e09b0c044c1b47d76f15629/tests/tests.py#L70) is commented out?\r\n \r\n## Steps to Reproduce\r\n1. Make yourself at home in an AWS Linux AMI\r\n2. Create a virtualenv and activate it.\r\n3. `pip install` a bunch of stuff, such as the requirements for you app\r\n4. See for yourself how there is a bunch of stuff installed in dist-packages\r\n5. do `zappa --package`\r\n6. compare the size of the lambda.zip with one made on non-debian distribution (it's smaller, because it doesn't include the packages from your virtualenv)\r\n7. see how the thing fails with unmet dependencies if you deploy it\r\n8. see how the lambda.zip does not contain your requirements\r\n\r\n## Your Environment\r\n* Zappa version used: latest\r\n* Operating System and Python version: Amazon Linux AMI\r\n* The output of `pip freeze`: any\r\n* Link to your project (optional): N/A\r\n* Your `zappa_settings.py`: N/A (I think)\r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/246/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/246/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/zappa/Zappa/issues/241", "repository_url": "https://api.github.com/repos/zappa/Zappa", "labels_url": "https://api.github.com/repos/zappa/Zappa/issues/241/labels{/name}", "comments_url": "https://api.github.com/repos/zappa/Zappa/issues/241/comments", "events_url": "https://api.github.com/repos/zappa/Zappa/issues/241/events", "html_url": "https://github.com/zappa/Zappa/issues/241", "id": 812550896, "node_id": "MDU6SXNzdWU4MTI1NTA4OTY=", "number": 241, "title": "[Migrated] Zappa certify fails on/after waiting for DNS propagation", "user": {"login": "jneves", "id": 53665, "node_id": "MDQ6VXNlcjUzNjY1", "avatar_url": "https://avatars.githubusercontent.com/u/53665?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jneves", "html_url": "https://github.com/jneves", "followers_url": "https://api.github.com/users/jneves/followers", "following_url": "https://api.github.com/users/jneves/following{/other_user}", "gists_url": "https://api.github.com/users/jneves/gists{/gist_id}", "starred_url": "https://api.github.com/users/jneves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jneves/subscriptions", "organizations_url": "https://api.github.com/users/jneves/orgs", "repos_url": "https://api.github.com/users/jneves/repos", "events_url": "https://api.github.com/users/jneves/events{/privacy}", "received_events_url": "https://api.github.com/users/jneves/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 2204045777, "node_id": "MDU6TGFiZWwyMjA0MDQ1Nzc3", "url": "https://api.github.com/repos/zappa/Zappa/labels/bug", "name": "bug", "color": "d73a4a", "default": true, "description": "Something isn't working"}, {"id": 2757112021, "node_id": "MDU6TGFiZWwyNzU3MTEyMDIx", "url": "https://api.github.com/repos/zappa/Zappa/labels/python3", "name": "python3", "color": "ededed", "default": false, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-02-20T08:23:38Z", "updated_at": "2021-02-20T16:07:52Z", "closed_at": "2021-02-20T16:07:52Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Originally from: https://github.com/Miserlou/Zappa/issues/887 by [GeoTob](https://github.com/GeoTob)\n\n## Context\r\nRunning zappa 0.42.0 on py3.6, I followed the \"custom domain with LE\" part of the documentation. I got to the \"waiting for DNS propagation\" stage, which after ~45s errors with:\r\n\r\n```\r\nSetting DNS challenge..\r\nWaiting for DNS to propagate..\r\nObject of type 'bytes' is not JSON serializable\r\n```\r\n \r\n## Possible Fix\r\nWhen `letsencrypt._send_signed_request` is called, `keyAuthorization` is passed as bytes and not string.\r\n\r\nThis fixes the issue but is far from elegant:\r\n```py\r\ndef _send_signed_request(url, payload):\r\n    \"\"\"\r\n    Helper function to make signed requests to Boulder\r\n    \"\"\"\r\n\r\n    if 'keyAuthorization' in payload:\r\n        try:\r\n            payload['keyAuthorization'] = payload['keyAuthorization'].decode()\r\n        except AttributeError:\r\n            pass\r\n```\r\n\r\n## Your Environment\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n* Zappa version used: 0.42.0\r\n* Operating System and Python version: ubuntu16.04/py3.6\r\n", "reactions": {"url": "https://api.github.com/repos/zappa/Zappa/issues/241/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/zappa/Zappa/issues/241/timeline", "performed_via_github_app": null, "state_reason": "completed"}]